apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: tanzu-addons-apiserver
  name: tanzu-addons-apiserver-sa
  namespace: tkg-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu-addons-apiserver-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  # Aggregated API server
  - apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservices
    verbs:
      - get
      - create
      - update
  # TODO revisit these permissions
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "watch", "get", "update"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["list", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["list", "watch"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
  - apiGroups: ["flowcontrol.apiserver.k8s.io"]
    resources: ["prioritylevelconfigurations", "flowschemas"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-addons-apiserver-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-addons-apiserver-clusterrole
subjects:
  - kind: ServiceAccount
    name: tanzu-addons-apiserver-sa
    namespace: tkg-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tanzu-addons-apiserver
  name: tanzu-addons-apiserver
  namespace: tkg-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tanzu-addons-apiserver
  template:
    metadata:
      labels:
        app: tanzu-addons-apiserver
    spec:
      containers:
        - image: projects-stg.registry.vmware.com/tkg/vkatam/addons-apiserver:v0.6.0-dev-18-gd5c497f4-dirty
          imagePullPolicy: Always
          name: tanzu-addons-apiserver
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 40Mi
      serviceAccount: tanzu-addons-apiserver-sa
      terminationGracePeriodSeconds: 10
      hostNetwork: true
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.addon.tanzu.vmware.com
spec:
  group: addon.tanzu.vmware.com
  groupPriorityMinimum: 100
  version: v1alpha1
  versionPriority: 100
  service:
    name: addons-apiserver
    namespace: tkg-system
---
apiVersion: v1
kind: Service
metadata:
  name: addons-apiserver
  namespace: tkg-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 10299
  selector:
    app: tanzu-addons-apiserver
