apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
  - path: config/upstream
    contents:
      - path: addons-manager.yaml
        manual: {}
      - path: cni.tanzu.vmware.com_antreaconfigs.yaml
        git:
          url: git@github.com:vmware-tanzu/tanzu-framework.git
          ref: 9ed3b1664b261d2d5c9dac552f8a2cc97168caf5
        newRootPath: config/crd/bases/cni.tanzu.vmware.com_antreaconfigs.yaml
        includePaths:
          - config/crd/bases/cni.tanzu.vmware.com_antreaconfigs.yaml
      - path: cni.tanzu.vmware.com_calicoconfigs.yaml
        git:
          url: git@github.com:vmware-tanzu/tanzu-framework.git
          ref: 9ed3b1664b261d2d5c9dac552f8a2cc97168caf5
        newRootPath: config/crd/bases/cni.tanzu.vmware.com_calicoconfigs.yaml
        includePaths:
          - config/crd/bases/cni.tanzu.vmware.com_calicoconfigs.yaml
      - path: run.tanzu.vmware.com_clusterbootstraps.yaml
        git:
          url: git@github.com:vmware-tanzu/tanzu-framework.git
          ref: 9ed3b1664b261d2d5c9dac552f8a2cc97168caf5
        newRootPath: config/crd/bases/run.tanzu.vmware.com_clusterbootstraps.yaml
        includePaths:
          - config/crd/bases/run.tanzu.vmware.com_clusterbootstraps.yaml
      - path: run.tanzu.vmware.com_clusterbootstraptemplates.yaml
        git:
          url: git@github.com:vmware-tanzu/tanzu-framework.git
          ref: 9ed3b1664b261d2d5c9dac552f8a2cc97168caf5
        newRootPath: config/crd/bases/run.tanzu.vmware.com_clusterbootstraptemplates.yaml
        includePaths:
          - config/crd/bases/run.tanzu.vmware.com_clusterbootstraptemplates.yaml
      - path: run.tanzu.vmware.com_kappcontrollerconfigs.yaml
        git:
          url: git@github.com:vmware-tanzu/tanzu-framework.git
          ref: 9ed3b1664b261d2d5c9dac552f8a2cc97168caf5
        newRootPath: config/crd/bases/run.tanzu.vmware.com_kappcontrollerconfigs.yaml
        includePaths:
          - config/crd/bases/run.tanzu.vmware.com_kappcontrollerconfigs.yaml
      - path: cpi.tanzu.vmware.com_cpiconfigs.yaml
        git:
          url: git@github.com:vmware-tanzu/tanzu-framework.git
          ref: 9ed3b1664b261d2d5c9dac552f8a2cc97168caf5
        newRootPath: config/crd/bases/cpi.tanzu.vmware.com_cpiconfigs.yaml
        includePaths:
          - config/crd/bases/cpi.tanzu.vmware.com_cpiconfigs.yaml
  - path: config/overlays
    contents:
      - path: feature-gate-clusterbootstrap.yaml
        manual: {}
