// +build !ignore_autogenerated

// Copyright 2021 VMware, Inc. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AntreaAddonConfig) DeepCopyInto(out *AntreaAddonConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AntreaAddonConfig.
func (in *AntreaAddonConfig) DeepCopy() *AntreaAddonConfig {
	if in == nil {
		return nil
	}
	out := new(AntreaAddonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AntreaAddonConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AntreaAddonConfigList) DeepCopyInto(out *AntreaAddonConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AntreaAddonConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AntreaAddonConfigList.
func (in *AntreaAddonConfigList) DeepCopy() *AntreaAddonConfigList {
	if in == nil {
		return nil
	}
	out := new(AntreaAddonConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AntreaAddonConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AntreaAddonConfigSpec) DeepCopyInto(out *AntreaAddonConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AntreaAddonConfigSpec.
func (in *AntreaAddonConfigSpec) DeepCopy() *AntreaAddonConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AntreaAddonConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AntreaAddonConfigStatus) DeepCopyInto(out *AntreaAddonConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AntreaAddonConfigStatus.
func (in *AntreaAddonConfigStatus) DeepCopy() *AntreaAddonConfigStatus {
	if in == nil {
		return nil
	}
	out := new(AntreaAddonConfigStatus)
	in.DeepCopyInto(out)
	return out
}
