// +build !ignore_autogenerated

// Copyright 2021 VMware, Inc. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AntreaAddonConfig) DeepCopyInto(out *AntreaAddonConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AntreaAddonConfig.
func (in *AntreaAddonConfig) DeepCopy() *AntreaAddonConfig {
	if in == nil {
		return nil
	}
	out := new(AntreaAddonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AntreaAddonConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AntreaAddonConfigList) DeepCopyInto(out *AntreaAddonConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AntreaAddonConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AntreaAddonConfigList.
func (in *AntreaAddonConfigList) DeepCopy() *AntreaAddonConfigList {
	if in == nil {
		return nil
	}
	out := new(AntreaAddonConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AntreaAddonConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AntreaAddonConfigSpec) DeepCopyInto(out *AntreaAddonConfigSpec) {
	*out = *in
	if in.ServiceCIDR != nil {
		in, out := &in.ServiceCIDR, &out.ServiceCIDR
		*out = new(string)
		**out = **in
	}
	if in.TrafficEncapMode != nil {
		in, out := &in.TrafficEncapMode, &out.TrafficEncapMode
		*out = new(string)
		**out = **in
	}
	if in.NoSNAT != nil {
		in, out := &in.NoSNAT, &out.NoSNAT
		*out = new(bool)
		**out = **in
	}
	if in.TlsCipherSuites != nil {
		in, out := &in.TlsCipherSuites, &out.TlsCipherSuites
		*out = new(string)
		**out = **in
	}
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = new(FeatureGates)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AntreaAddonConfigSpec.
func (in *AntreaAddonConfigSpec) DeepCopy() *AntreaAddonConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AntreaAddonConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AntreaAddonConfigStatus) DeepCopyInto(out *AntreaAddonConfigStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AntreaAddonConfigStatus.
func (in *AntreaAddonConfigStatus) DeepCopy() *AntreaAddonConfigStatus {
	if in == nil {
		return nil
	}
	out := new(AntreaAddonConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureGates) DeepCopyInto(out *FeatureGates) {
	*out = *in
	if in.AntreaProxy != nil {
		in, out := &in.AntreaProxy, &out.AntreaProxy
		*out = new(bool)
		**out = **in
	}
	if in.EndpointSlice != nil {
		in, out := &in.EndpointSlice, &out.EndpointSlice
		*out = new(bool)
		**out = **in
	}
	if in.AntreaPolicy != nil {
		in, out := &in.AntreaPolicy, &out.AntreaPolicy
		*out = new(bool)
		**out = **in
	}
	if in.NodePortLocal != nil {
		in, out := &in.NodePortLocal, &out.NodePortLocal
		*out = new(bool)
		**out = **in
	}
	if in.AntreaTraceflow != nil {
		in, out := &in.AntreaTraceflow, &out.AntreaTraceflow
		*out = new(bool)
		**out = **in
	}
	if in.FlowExporter != nil {
		in, out := &in.FlowExporter, &out.FlowExporter
		*out = new(bool)
		**out = **in
	}
	if in.NetworkPolicyStats != nil {
		in, out := &in.NetworkPolicyStats, &out.NetworkPolicyStats
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureGates.
func (in *FeatureGates) DeepCopy() *FeatureGates {
	if in == nil {
		return nil
	}
	out := new(FeatureGates)
	in.DeepCopyInto(out)
	return out
}
