apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "14"
    kapp.k14s.io/disable-default-label-scoping-rules: ""
    kapp.k14s.io/identity: v1;kube-system/apps/DaemonSet/antrea-agent;apps/v1
    kapp.k14s.io/original: '{"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{"kapp.k14s.io/disable-default-label-scoping-rules":"","kbld.k14s.io/images":"-
      Metas:\n  - Type: preresolved\n    URL: projects-stg.registry.vmware.com/tkg/antrea/antrea-debian@sha256:8a4c3f719bec5eb3d6b4a73fc8156a8d7137418f7788ae29b1226f820df1b102\n  URL:
      projects-stg.registry.vmware.com/tkg/antrea/antrea-debian@sha256:8a4c3f719bec5eb3d6b4a73fc8156a8d7137418f7788ae29b1226f820df1b102\n"},"labels":{"app":"antrea","component":"antrea-agent","kapp.k14s.io/app":"1631924531358703241","kapp.k14s.io/association":"v1.076f01a42f753f381f6e08defd96ce2f"},"name":"antrea-agent","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"app":"antrea","component":"antrea-agent"}},"template":{"metadata":{"labels":{"app":"antrea","component":"antrea-agent","kapp.k14s.io/app":"1631924531358703241","kapp.k14s.io/association":"v1.076f01a42f753f381f6e08defd96ce2f"}},"spec":{"containers":[{"args":["--config","/etc/antrea/antrea-agent.conf","--logtostderr=false","--log_dir=/var/log/antrea","--alsologtostderr","--log_file_max_size=100","--log_file_max_num=4","--v=0"],"command":["antrea-agent"],"env":[{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}}],"image":"projects-stg.registry.vmware.com/tkg/antrea/antrea-debian@sha256:8a4c3f719bec5eb3d6b4a73fc8156a8d7137418f7788ae29b1226f820df1b102","imagePullPolicy":"IfNotPresent","livenessProbe":{"exec":{"command":["/bin/sh","-c","container_liveness_probe
      agent"]},"failureThreshold":5,"initialDelaySeconds":5,"periodSeconds":10,"timeoutSeconds":5},"name":"antrea-agent","ports":[{"containerPort":10350,"name":"api","protocol":"TCP"}],"readinessProbe":{"failureThreshold":5,"httpGet":{"host":"127.0.0.1","path":"/readyz","port":"api","scheme":"HTTPS"},"initialDelaySeconds":5,"periodSeconds":10,"timeoutSeconds":5},"resources":{"requests":{"cpu":"200m"}},"securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/etc/antrea/antrea-agent.conf","name":"antrea-config","readOnly":true,"subPath":"antrea-agent.conf"},{"mountPath":"/var/run/antrea","name":"host-var-run-antrea"},{"mountPath":"/var/run/openvswitch","name":"host-var-run-antrea","subPath":"openvswitch"},{"mountPath":"/var/lib/cni","name":"host-var-run-antrea","subPath":"cni"},{"mountPath":"/var/log/antrea","name":"host-var-log-antrea"},{"mountPath":"/host/proc","name":"host-proc","readOnly":true},{"mountPath":"/host/var/run/netns","mountPropagation":"HostToContainer","name":"host-var-run-netns","readOnly":true},{"mountPath":"/run/xtables.lock","name":"xtables-lock"}]},{"args":["--log_file_max_size=100","--log_file_max_num=4"],"command":["start_ovs"],"image":"projects-stg.registry.vmware.com/tkg/antrea/antrea-debian@sha256:8a4c3f719bec5eb3d6b4a73fc8156a8d7137418f7788ae29b1226f820df1b102","imagePullPolicy":"IfNotPresent","livenessProbe":{"exec":{"command":["/bin/sh","-c","timeout
      10 container_liveness_probe ovs"]},"failureThreshold":5,"initialDelaySeconds":5,"periodSeconds":10,"timeoutSeconds":10},"name":"antrea-ovs","resources":{"requests":{"cpu":"200m"}},"securityContext":{"capabilities":{"add":["SYS_NICE","NET_ADMIN","SYS_ADMIN","IPC_LOCK"]}},"volumeMounts":[{"mountPath":"/var/run/openvswitch","name":"host-var-run-antrea","subPath":"openvswitch"},{"mountPath":"/var/log/openvswitch","name":"host-var-log-antrea","subPath":"openvswitch"}]}],"dnsPolicy":"ClusterFirstWithHostNet","hostNetwork":true,"initContainers":[{"command":["install_cni"],"image":"projects-stg.registry.vmware.com/tkg/antrea/antrea-debian@sha256:8a4c3f719bec5eb3d6b4a73fc8156a8d7137418f7788ae29b1226f820df1b102","imagePullPolicy":"IfNotPresent","name":"install-cni","resources":{"requests":{"cpu":"100m"}},"securityContext":{"capabilities":{"add":["SYS_MODULE"]}},"volumeMounts":[{"mountPath":"/etc/antrea/antrea-cni.conflist","name":"antrea-config","readOnly":true,"subPath":"antrea-cni.conflist"},{"mountPath":"/host/etc/cni/net.d","name":"host-cni-conf"},{"mountPath":"/host/opt/cni/bin","name":"host-cni-bin"},{"mountPath":"/lib/modules","name":"host-lib-modules","readOnly":true},{"mountPath":"/var/run/antrea","name":"host-var-run-antrea"}]}],"nodeSelector":{"kubernetes.io/os":"linux"},"priorityClassName":"system-node-critical","serviceAccountName":"antrea-agent","tolerations":[{"key":"CriticalAddonsOnly","operator":"Exists"},{"effect":"NoSchedule","operator":"Exists"},{"effect":"NoExecute","operator":"Exists"}],"volumes":[{"configMap":{"name":"antrea-config-ctb8mftc58"},"name":"antrea-config"},{"hostPath":{"path":"/etc/cni/net.d"},"name":"host-cni-conf"},{"hostPath":{"path":"/opt/cni/bin"},"name":"host-cni-bin"},{"hostPath":{"path":"/proc"},"name":"host-proc"},{"hostPath":{"path":"/var/run/netns"},"name":"host-var-run-netns"},{"hostPath":{"path":"/var/run/antrea","type":"DirectoryOrCreate"},"name":"host-var-run-antrea"},{"hostPath":{"path":"/var/log/antrea","type":"DirectoryOrCreate"},"name":"host-var-log-antrea"},{"hostPath":{"path":"/lib/modules"},"name":"host-lib-modules"},{"hostPath":{"path":"/run/xtables.lock","type":"FileOrCreate"},"name":"xtables-lock"}]}},"updateStrategy":{"type":"RollingUpdate"}}}'
    kapp.k14s.io/original-diff-md5: fc2e0329b65f39432464e2199d22b1b8
    kbld.k14s.io/images: |
      - Metas:
        - Type: preresolved
          URL: projects-stg.registry.vmware.com/tkg/antrea/antrea-debian@sha256:8a4c3f719bec5eb3d6b4a73fc8156a8d7137418f7788ae29b1226f820df1b102
        URL: projects-stg.registry.vmware.com/tkg/antrea/antrea-debian@sha256:8a4c3f719bec5eb3d6b4a73fc8156a8d7137418f7788ae29b1226f820df1b102
  creationTimestamp: "2021-09-18T00:18:15Z"
  generation: 17
  labels:
    app: antrea
    component: antrea-agent
    kapp.k14s.io/app: "1631924531358703241"
    kapp.k14s.io/association: v1.076f01a42f753f381f6e08defd96ce2f
  name: antrea-agent
  namespace: kube-system
  uid: 918226d4-c0ac-44f8-ab03-0a227e21981c
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: antrea
      component: antrea-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: antrea
        component: antrea-agent
        kapp.k14s.io/app: "1631924531358703241"
        kapp.k14s.io/association: v1.076f01a42f753f381f6e08defd96ce2f
        foo: barbaz
    spec:
      containers:
      - args:
        - --config
        - /etc/antrea/antrea-agent.conf
        - --logtostderr=false
        - --log_dir=/var/log/antrea
        - --alsologtostderr
        - --log_file_max_size=100
        - --log_file_max_num=4
        - --v=0
        command:
        - antrea-agent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: projects-stg.registry.vmware.com/tkg/antrea/antrea-debian@sha256:8a4c3f719bec5eb3d6b4a73fc8156a8d7137418f7788ae29b1226f820df1b102
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - container_liveness_probe agent
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: antrea-agent
        ports:
        - containerPort: 10350
          hostPort: 10350
          name: api
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            host: 127.0.0.1
            path: /readyz
            port: api
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 200m
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/antrea/antrea-agent.conf
          name: antrea-config
          readOnly: true
          subPath: antrea-agent.conf
        - mountPath: /var/run/antrea
          name: host-var-run-antrea
        - mountPath: /var/run/openvswitch
          name: host-var-run-antrea
          subPath: openvswitch
        - mountPath: /var/lib/cni
          name: host-var-run-antrea
          subPath: cni
        - mountPath: /var/log/antrea
          name: host-var-log-antrea
        - mountPath: /host/proc
          name: host-proc
          readOnly: true
        - mountPath: /host/var/run/netns
          mountPropagation: HostToContainer
          name: host-var-run-netns
          readOnly: true
        - mountPath: /run/xtables.lock
          name: xtables-lock
      - args:
        - --log_file_max_size=100
        - --log_file_max_num=4
        command:
        - start_ovs
        image: projects-stg.registry.vmware.com/tkg/antrea/antrea-debian@sha256:8a4c3f719bec5eb3d6b4a73fc8156a8d7137418f7788ae29b1226f820df1b102
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - timeout 10 container_liveness_probe ovs
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: antrea-ovs
        resources:
          requests:
            cpu: 200m
        securityContext:
          capabilities:
            add:
            - SYS_NICE
            - NET_ADMIN
            - SYS_ADMIN
            - IPC_LOCK
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/openvswitch
          name: host-var-run-antrea
          subPath: openvswitch
        - mountPath: /var/log/openvswitch
          name: host-var-log-antrea
          subPath: openvswitch
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      initContainers:
      - command:
        - install_cni
        image: projects-stg.registry.vmware.com/tkg/antrea/antrea-debian@sha256:8a4c3f719bec5eb3d6b4a73fc8156a8d7137418f7788ae29b1226f820df1b102
        imagePullPolicy: IfNotPresent
        name: install-cni
        resources:
          requests:
            cpu: 100m
        securityContext:
          capabilities:
            add:
            - SYS_MODULE
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/antrea/antrea-cni.conflist
          name: antrea-config
          readOnly: true
          subPath: antrea-cni.conflist
        - mountPath: /host/etc/cni/net.d
          name: host-cni-conf
        - mountPath: /host/opt/cni/bin
          name: host-cni-bin
        - mountPath: /lib/modules
          name: host-lib-modules
          readOnly: true
        - mountPath: /var/run/antrea
          name: host-var-run-antrea
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: antrea-agent
      serviceAccountName: antrea-agent
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          name: antrea-config-ctb8mftc58
        name: antrea-config
      - hostPath:
          path: /etc/cni/net.d
          type: ""
        name: host-cni-conf
      - hostPath:
          path: /opt/cni/bin
          type: ""
        name: host-cni-bin
      - hostPath:
          path: /proc
          type: ""
        name: host-proc
      - hostPath:
          path: /var/run/netns
          type: ""
        name: host-var-run-netns
      - hostPath:
          path: /var/run/antrea
          type: DirectoryOrCreate
        name: host-var-run-antrea
      - hostPath:
          path: /var/log/antrea
          type: DirectoryOrCreate
        name: host-var-log-antrea
      - hostPath:
          path: /lib/modules
          type: ""
        name: host-lib-modules
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1%
    type: RollingUpdate
status:
  currentNumberScheduled: 2
  desiredNumberScheduled: 2
  numberAvailable: 2
  numberMisscheduled: 0
  numberReady: 2
  observedGeneration: 17
  updatedNumberScheduled: 2
